run:
  timeout: 5m

linters:
  enable:
    - errcheck
#    - gosimple // for clarity and control over field mapping
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goimports
    - bodyclose
    - sloglint
    - unconvert
    - gosec
    - noctx
    - gocritic
    - testifylint
    - goconst
    - nilerr
    - contextcheck
    - whitespace
    - typecheck
