services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8088:8088"
    restart: on-failure
    depends_on:
        postgres:
          condition: service_healthy

  postgres:
    image: postgres:16
    environment:
      - "POSTGRES_DB=${DB_DATABASE}"
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    ports:
      - "${DB_HOST_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-}" ]
        interval: 30s
        timeout: 30s
        retries: 3
        start_period: 10s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - '8888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: password

volumes:
  pgdata:
