services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
        postgres:
          condition: service_healthy

  postgres:
    image: postgres:16
    environment:
      - "POSTGRES_DB=${DB_NAME}"
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    ports:
      - "${DB_HOST_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-}" ]
        interval: 5s
        timeout: 10s
        retries: 3
        start_period: 15s

volumes:
  pgdata:
