global:
  scrape_interval: 15s  # How frequently to scrape targets

scrape_configs:
  - job_name: 'app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:8082']  # Prometheus will scrape metrics from the app container on port 8082
