global:
  scrape_interval: 15s  # How frequently to scrape targets

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: ['app:8082']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

