app:
  port: "8088"

metrics:
  port: "8082"

cache:
  expirationMinutes: 10
  cleanupMinutes: 5

db:
  user: "postgres"
  password: "postgres"
  host: "postgres"
  port: "5432"
  name: "postgres"

logger:
  level: "info"

tracing:
  jaegerEndpoint: "jaeger:4318"
