name: Lint

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  golangci-lint:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.8

      - name: Download Go modules
        run: go mod download

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.64.8

      - name: Run golangci-lint
        run: golangci-lint run

  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.8

      - name: Download Go modules
        run: go mod download

      - name: Run unit tests
        run: go test -v ./...